### PR TITLE
Update for Atom v1.13.0 (resolve - #26)

### PR DESCRIPTION
**Pull request by tyrollins**
Updated syntax for Atom v1.13

Went down the list and plugged in the updated syntax as directed by Atom's deprecation cop, so all colors etc... should remain unchanged.

Cheers for the theme.

### CODE REVIEW

**Comment by trevordmiller** [comment]
This PR seems to have broken things:
https://twitter.com/keithjgrant/status/829702550706327556

Would appreciate testing and a fix if you have time @tyrollins :)

**Comment by tyrollins** [comment]
hmmm... I'll check it out today, see if I can reproduce, as to provide fix. Works on my end with Atom v >= 1.13 so not sure, maybe it's a versioning thing...I'll try and get to the bottom of it today. Cheers.

**Comment by trevordmiller** [comment]
@tyrollins Thank you. I don't use Atom so I didn't notice this but I just opened it and upgraded and I'm getting the same thing:
image

image

**Comment by tyrollins** [comment]
@trevordmiller Curious... All is working as expected on my machine w/ Atom / Atom-Beta. What version number is your Atom Editor? Additionally, does the syntax theme work with a different UI Theme, or is it still all white? I'll continue to search for the problem but your atom version number would help. Cheers.

**Comment by trevordmiller** [comment]
@tyrollins Upgrading to latest Atom solved it - thank you!

**Comment by tyrollins** [comment]
@trevordmiller 
OK brilliant, with Atom ~ v1.13 the class names changed - (.syntax--cursor instead of just .cursor) - this is probably the reason why the theme was not working properly. It's highly likely the user who reported this issue, was using an older version of Atom as well. All should work for v1.13 and later. (users are encouraged to update atom to at least v1.13 anyways, as there were editor / performance improvements.)

That said, since I did not experience the issue, I am not 100% as to the cause (fairly certain the above was the issue though). Please let me know if you run into any other problems, and I'll do what I can to sort them ASAP. 

Cheers.

**Comment by trevordmiller** [comment]
@tyrollins I think you are right. I think we are good for now. Thank  you very much for your time and help :)

**Pull request merged**
